"""Run history + manual trigger handlers (user-scoped)."""

from __future__ import annotations

import json
import logging
import os
from typing import Any

import boto3
from boto3.dynamodb.conditions import Key

from src.api._errors import HttpError
from src.api._user_repo import decimals_to_native

logger = logging.getLogger(__name__)


def list_runs(user_id: str, limit: int = 25) -> list[dict[str, Any]]:
    """Return recent runs for this user (newest first).

    Projects `guardrail_triggers` from its persisted forensic shape
    (`[{"node": "...", "errors": [...], "timestamp": "..."}]`) down to the
    list of node-name strings the dashboard renders. The full dict-shaped
    detail stays in the row for later audit/inspection endpoints.
    """
    table = boto3.resource("dynamodb").Table(os.environ["RUNS_TABLE_NAME"])
    resp = table.query(
        IndexName="user-id-index",
        KeyConditionExpression=Key("user_id").eq(user_id),
        ScanIndexForward=False,  # newest first
        Limit=limit,
    )
    items = resp.get("Items", [])
    # Strip the heavy config_snapshot from list view to keep response small;
    # callers can fetch individual runs in detail if we add that endpoint later.
    trimmed = [{k: v for k, v in item.items() if k != "config_snapshot"} for item in items]
    for row in trimmed:
        row["guardrail_triggers"] = _flatten_trigger_names(row.get("guardrail_triggers"))
    return decimals_to_native(trimmed)


def _flatten_trigger_names(raw: Any) -> list[str]:
    """Coerce `guardrail_triggers` (legacy dict shape or already-strings) to
    a list of node-name strings. Anything unparseable becomes `[]` rather
    than poisoning the whole response — the dashboard parses runs strictly,
    so a single bad row would otherwise blank the recent-runs list.
    """
    if not isinstance(raw, list):
        return []
    out: list[str] = []
    for item in raw:
        if isinstance(item, str):
            out.append(item)
        elif isinstance(item, dict):
            node = item.get("node")
            if isinstance(node, str):
                out.append(node)
    return out


def trigger_run(user_id: str) -> dict[str, Any]:
    """Drop a per-user run message onto the SQS queue.

    The worker picks it up asynchronously. Returns 202-style ACCEPTED with the
    SQS MessageId — the actual run_id is generated by the worker and shows up
    in the runs table once it completes (typically within a minute or two).

    Rejects with 409 Conflict when a run is already in flight for this user
    (defense in depth — the dashboard also disables the button while a run is
    underway, but stale tabs and direct API hits should not double-queue).
    """
    queue_url = os.environ.get("RUNS_QUEUE_URL", "")
    if not queue_url:
        raise HttpError(503, "Worker queue not configured (RUNS_QUEUE_URL missing)")

    from src.memory import run_state

    in_flight = run_state.get_in_flight(user_id)
    if in_flight:
        raise HttpError(
            409,
            "A run is already underway for this account",
            details={
                "run_id": in_flight.get("run_id"),
                "started_at": in_flight.get("started_at"),
                "current_node": in_flight.get("current_node"),
            },
        )

    sqs = boto3.client("sqs")
    try:
        resp = sqs.send_message(
            QueueUrl=queue_url,
            MessageBody=json.dumps({"user_id": user_id, "trigger": "manual"}),
        )
    except Exception as e:
        logger.exception("Failed to enqueue run for user_id=%s", user_id)
        raise HttpError(502, "Failed to queue run", details={"detail": str(e)}) from e

    return {
        "status": "ACCEPTED",
        "message_id": resp.get("MessageId"),
        "user_id": user_id,
    }


def get_in_flight_run(user_id: str) -> dict[str, Any]:
    """Report whether a run is currently underway for this user.

    Shape: `{ in_flight: bool, run_id?, started_at?, current_node?,
    progress?: {completed, total} }`. Frontend polls this at 3-5s while
    in-flight to drive the progress bar; on tab focus otherwise.
    """
    from src.memory import run_state

    item = run_state.get_in_flight(user_id)
    if not item:
        return {"in_flight": False}
    out: dict[str, Any] = {
        "in_flight": True,
        "run_id": item.get("run_id"),
        "started_at": item.get("started_at"),
        "current_node": item.get("current_node"),
    }
    completed = item.get("progress_completed")
    total = item.get("progress_total")
    if completed is not None and total is not None:
        out["progress"] = {"completed": completed, "total": total}
    return out
